services:
  mysql:
    image: 'mysql:8.3.0'
    environment:
      - 'MYSQL_DATABASE=pelikan-dev-db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
