version: '3'

services:
  mysql:
    image: mysql:8.3.0
    container_name: 'pelican-mysql'
    restart: 'on-failure'
    network_mode: 'host' # I used this to share the network with the machine - do not need to modify the localhost (dev purposes - now runs both ways - docker or IDE run SpringbootApplication class)
    environment:
      - 'MYSQL_DATABASE=pelican_dev_db'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    volumes:
      - ./src/main/resources/docker/manual/mysql-init:/init-scripts
    command: >
      --init-file /init-scripts/init.sql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", 'mysql -h localhost -u myuser -psecret -e "USE pelican_dev_db; SELECT 1 FROM post LIMIT 1;"'] # could not run flyway in docker - I init table + perms to user in init.sql
      interval: 20s
      retries: 10
      timeout: 30s

  pelican-api:
    depends_on:
      mysql:
        condition: 'service_healthy'
    network_mode: 'host' # I used this to share the network with the machine - do not need to modify the localhost (dev purposes - now runs both ways - docker or IDE run SpringbootApplication class)
    build: .
    restart: 'on-failure'
    ports:
      - '9090:9090'
