spring:
  datasource:
    url: '@spring.datasource.url@'
    username: '@spring.datasource.username@'
    password: '@spring.datasource.password@'
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    locations:  classpath:db/dev/migration    
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    out-of-order: true
  docker:
    compose:
      enabled: true
      file: classpath:docker/dev/docker-compose.yml